# The URL the site will be built for
# base_url = "http://ir.hit.edu.cn/~la"
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "publisher", feed = true, lang = "en" },
    { name = "publisher", feed = true, lang = "zh" },
    { name = "publish_year", feed = true, lang = "en" },
    { name = "publish_year", feed = true, lang = "zh" },
    { name = "authors", feed = true, lang = "en" },
    { name = "authors", feed = true, lang = "zh" },
    { name = "news_type", feed = true, lang = "en" },
    { name = "news_type", feed = true, lang = "zh" },
    { name = "direction", feed = true, lang = "en" },
    { name = "direction", feed = true, lang = "zh" },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[slugify]
    taxonomies = "on"

[extra]
# Put all your custom variables here
